navigator:
  item:
    type: COMPASS
    slot: 0
  gui:
    size: 36
    customizable: true
  icons:
    customizable: false
  close_action:
    enabled: false
  teleport_message:
    enabled: true
  lobby_spawn:
    slot: 0
    item: COMPASS
    coordinates: [0, 64, 0]
  notifications:
    new_players_only: true
    always: true
  teleport_delay: 3
  teleport_message: true
  permissions:
    spawn: lynx.navigator.spawn
  sounds:
    open_gui: ENTITY_PLAYER_LEVELUP
    teleport: ENTITY_ENDERMAN_TELEPORT
  visual_effects:
    enabled: true
    type: SMOKE
    color: GRAY