lobby:
  x: 0
  y: 64
  z: 0
  teleport-delay: 3
  custom-teleport-message: "You have been teleported to the Lobby."

minigames: {}  # Empty for now, will be populated by commands
lobbyspawns: {}  # Empty for now, will be populated by commands