
name: LobbyLynx
version: '1.0'
main: org.derjannik.lobbylynx.LobbyLynx
api-version: '1.20'
commands:
  setminigame:
    description: Set a minigame location
    usage: /<command> <minigame_name> <slot> <item_id/name> <x> <y> <z>
    permission: lynx.admin.setminigame
  setlobbyspawn:
    description: Set the lobby spawn location
    usage: /<command> <slot> <item_id/name> <x> <y> <z>
    permission: lynx.admin.setlobbyspawn
  lobby:
    description: Teleport to the lobby spawn
    usage: /<command>
    permission: lynx.navigator.spawn
permissions:
  lynx.admin.setminigame:
    description: Allows setting minigame locations
    default: op
  lynx.admin.setlobbyspawn:
    description: Allows setting the lobby spawn location
    default: op
  lynx.navigator.spawn:
    description: Allows using the navigator and teleporting to the lobby
    default: true
