name: LobbyLynx
version: '1.0-SNAPSHOT'
main: org.derjannik.lobbyLynx.LobbyLynx
api-version: '1.21'
commands:
  lynx:
    description: Admin GUI
    usage: /<command> [settings] | /<command> [setlobby] | /<command> [setminigame] <name>
    permission: lynx.admin
  lobby:
    description: Teleport to the lobby
    usage: /lobby
permissions:
  lynx.admin:
    description: Grants access to all admin functionalities, commands, and settings.
    default: op # or 'true' if you want all players to have it by default